Graph500 SEQ
ocaml-bench/sandmark pull request #170
Opened 2020-08-26 15:04 UTC by singhalshubh

2020-08-27 05:22 UTC, kayceesrk commented
@singhalshubh Can you add a description of what the benchmark is and does in the PR? Please include links to the graph 500 website so that someone looking at this PR in the future has enough context.

2020-08-27 05:23 UTC, kayceesrk commented on benchmarks/graph500seq/kronecker.ml
> +    let ijw = ([firstRowIJW] @ [secondRowIJW] @ [List.nth ijw 2]) in compareWithPr (index+1) m n ab a_norm c_norm ijw scale
break to 80 cols

2020-08-27 05:35 UTC, kayceesrk requested changes

2020-08-27 05:35 UTC, kayceesrk commented on benchmarks/graph500seq/kronecker.ml
> +    headII::tailII, headList::tailList -> let element = headList +. (( 2. **float_of_int(index) ) *. headII) in modifyRowIJW (tailII) index (tailList) (element::newList)
break to 80 cols

2020-08-27 05:35 UTC, kayceesrk commented on benchmarks/graph500seq/kronecker.ml
> +    then generateJJBitList (1.::list) tail m a_norm c_norm else generateJJBitList (0.::list) tail m a_norm c_norm
break to 80 cols

2020-08-27 05:35 UTC, kayceesrk commented on benchmarks/graph500seq/kernel1.ml
> +(*Kernel 1 is basic construction of adjacency HashMap for undirected graphs which is corresponding to sparse graph implementation. INPUTS : ijw and m which has been
break to 80 cols

2020-08-27 05:35 UTC, kayceesrk commented on benchmarks/graph500seq/kernel1.ml
> +		head::tail -> let x = List.nth head 0 and y = List.nth head 1 in if x > y then sortVerticeList tail (newList@[[x;y;List.nth head 2]]) (max maximum x)
break to 80 cols. There are many more instances of long lines. Please use `ocamlformat`

2020-08-27 05:35 UTC, kayceesrk commented on benchmarks/graph500seq/kernel1.ml
> +(*As the name suggests, it removes the self loops from ijw*)
```suggestion
(* As the name suggests, it removes the self loops from [ijw] *)
```

2020-08-27 05:35 UTC, kayceesrk commented on benchmarks/graph500seq/kernel1.ml
> +(*let constructionAdjMatrix list maxLabel = let matrix = Array.make_matrix
Delete

2020-08-27 05:35 UTC, kayceesrk commented on benchmarks/graph500seq/kernel1.ml
> +(*This is basically the construction of adj matrix [row][col], just in case dense graphs are being tested. All the kernels further though use HashMap, and thus would
80 cols

2020-08-27 05:35 UTC, kayceesrk commented on benchmarks/graph500seq/kernel1.ml
> +	else removeSelfLoops ijw (newList@[ [(List.nth (List.nth ijw 0) col) ; (List.nth (List.nth ijw 1) col) ; (List.nth (List.nth ijw 2) col) ] ]) (col+1) m
80 cols

2020-08-27 05:35 UTC, kayceesrk commented on benchmarks/graph500seq/kernel1.ml
> +	head::tail -> let startVertex = int_of_float(List.nth head 0) and endVertex = int_of_float(List.nth head 1) and weight = List.nth head 2 in
Use `ocamlformat` and break to 80 cols

2020-08-27 05:35 UTC, kayceesrk commented on benchmarks/graph500seq/kernel1.ml
> +;;
Add a new line at the end of the file.

2020-08-27 05:35 UTC, kayceesrk commented on benchmarks/graph500seq/kernel1.ml
> +	let scale = int_of_string(Sys.argv.(1)) in
Take command line arguments at the top of the file. All the other benchmarks in sandmark are written this way. This way it is easier to know what arguments a program takes by looking at the top of the file rather than searching for it somewhere in the body.

2020-08-27 05:35 UTC, kayceesrk commented on benchmarks/graph500seq/kernel1.ml
> +	let adjMatrix = kernel1 (Kronecker.kronecker scale edgefactor) (snd(Kronecker.computeNumber scale edgefactor)) in adjMatrix
80 cols

2020-08-27 05:35 UTC, kayceesrk commented on benchmarks/graph500seq/kernel2.ml
> +(*This function iterates over the list which are adjacent to the node. So lets say for node n1, we have n2,n3,n4 nodes. THe list would be in the form of (node,wght)
80 cols

2020-08-27 05:35 UTC, kayceesrk commented on benchmarks/graph500seq/kernel2.ml
> +    head::tail -> if visited.(fst(head)) = 0 then let _ = parentArray.(fst(head)) <- parentVertex in appendVerticesToQueue parentVertex (queue @ [fst(head)]) tail parentArray visited
80 cols, ocamlformat

2020-08-27 05:35 UTC, kayceesrk commented on benchmarks/graph500seq/kernel2.ml
> +(*For debugging*)
Delete this commented code.

2020-08-27 05:35 UTC, kayceesrk commented on benchmarks/graph500seq/kernel2.ml
> +(*Main function is the function where it calls bfs. Size computation is using HashMap and the initialiszation of all arrays and lists happen here.*)
80 cols.

2020-08-27 05:35 UTC, kayceesrk commented on benchmarks/graph500seq/kernel2.ml
> +linkKernel1 ();;
new line

2020-08-27 05:35 UTC, kayceesrk commented on benchmarks/graph500seq/kronecker.ml
> +(*Kronecker is using the following algorithm :  Function Kronecker generator(scale, edgefactor) : N = 2^scale M =
This is hard to read and can be formatted better as OCaml could would be.

2020-08-27 05:35 UTC, kayceesrk commented on run_config.json
> +      "command": "orun -o %{output} -- taskset --cpu-list 3 %{command}"
Revert these changes. In general, have a local break where you experiement and avoid pushing changes that are only necessary locally.

2020-08-27 07:07 UTC, Sudha247 requested changes
* In general, I think it is a good idea to use OCaml standard library functions wherever possible. API docs for the modules in stdlib are available [here](https://caml.inria.fr/pub/docs/manual-ocaml/libref/).

* Hardcoding terminating conditions like `col = 3` in recursive functions could be avoided if possible. Hardcoding might make debugging harder than it usually is and it also restricts the scope of future use of those functions. I have left comments in some places about this, there might be other places I could've missed.

2020-08-27 11:00 UTC, singhalshubh commented on benchmarks/graph500seq/kernel1.ml
> +		in transpose list (col+1) (newList@[(transposeRow 0 [])])
The function is just a utility function. Its not being used anywhere, but is a way to test if data is correct between several functions.

2020-08-27 11:01 UTC, singhalshubh commented on benchmarks/graph500seq/kronecker.ml
> +  let _ = printList ijw in
its just for debugging. When merged anyway I ll remove it!

2020-08-27 11:02 UTC, singhalshubh commented on benchmarks/graph500seq/kronecker.ml
> +  if m = 0 then list else listGenerator1D (0.::list) (m-1)
It requires me to use Core. So I used this over List.init. Utop also suggests "no init"

2020-08-27 11:03 UTC, singhalshubh commented on benchmarks/graph500seq/kronecker.ml
> +    head::tail -> List.iter print_float head; printList tail
Just the utility function.

2020-08-27 11:04 UTC, singhalshubh commented on benchmarks/graph500seq/kernel3.ml
> +      else let _ = parentArray.(adjvertex) <- vertex in let _ = distanceArray.(adjvertex) <- (distanceArray.(vertex) +. snd(head)) in adjustDistance vertex tail distanceArray parentArray visited
As we discussed, there are some let _ due to which errors popped up. I have maximised the reduction of let _, but some of their removal requires me to change a lot of code. Please can we bear with just 3 let _?

2020-08-27 11:15 UTC, Sudha247 commented on benchmarks/graph500seq/kronecker.ml
> +  if m = 0 then list else listGenerator1D (0.::list) (m-1)
Which version of OCaml are you using? As I already mentioned, it is available in standard library. See here https://github.com/ocaml-multicore/ocaml-multicore/blob/parallel_minor_gc/stdlib/list.mli#L79-L84

2020-08-31 11:10 UTC, shakthimaan commented on benchmarks/graph500seq/dune
> +	(names kernel2 kernel3))
Use `width` as two spaces.

2020-08-31 11:14 UTC, shakthimaan commented on benchmarks/graph500seq/kernel1.ml
> +let sortVerticeList list newList =
Please use snake case, `sort_vertice_list`, style of naming functions.

2020-08-31 11:17 UTC, shakthimaan commented on benchmarks/graph500seq/kernel2.ml
> +        (*let _ = printList queue in*)
Remove commented code.

2020-08-31 11:18 UTC, shakthimaan commented on benchmarks/graph500seq/kernel2.ml
> +  (*Printf.printf "%d\n" len;*)
Remove commented code.

2020-08-31 11:20 UTC, shakthimaan commented on benchmarks/graph500seq/kernel2.ml
> +  Printf.printf "\nBfs Tree is : ";
When the benchmark runs are executed the output is always redirected to `/dev/null`, so the `printf` is not logged. You can remove them.

2020-08-31 11:22 UTC, shakthimaan commented on benchmarks/graph500seq/kernel3.ml
> +  then update the distance else continue with other nodes. Parent Array is also updated here.*)
Make sure to fit text within 80 columns, and also run spell-check. For example `haveto` should be `have to`.

2020-08-31 11:25 UTC, shakthimaan commented on benchmarks/graph500seq/kernel1.ml
> +    | head :: tail ->
The common OCaml idiom is to use `hd` for head, and `tl` for tail.

2020-08-31 11:32 UTC, shakthimaan commented on benchmarks/graph500seq/kernel3.ml
> +  let size = n in
Why not use just `n` everywhere, instead of re-assigning it to `size`?

2020-09-01 13:03 UTC, singhalshubh commented on benchmarks/graph500seq/dune
> +	(names kernel2 kernel3))
Done

2020-09-01 13:04 UTC, singhalshubh commented on benchmarks/graph500seq/kernel1.ml
> +let sortVerticeList list newList =
There are some of the function names which are quite long. Also, I would have to literally change the whole code. Can this be considered? I will keep in mind the next benchmark I make.

2020-09-01 13:05 UTC, singhalshubh commented on benchmarks/graph500seq/kernel2.ml
> +        (*let _ = printList queue in*)
How would someone understand the code then?

2020-09-01 13:05 UTC, singhalshubh commented on benchmarks/graph500seq/kernel2.ml
> +  Printf.printf "\nBfs Tree is : ";
They are just for debugging purposes!

2020-09-01 13:07 UTC, singhalshubh commented on benchmarks/graph500seq/kernel1.ml
> +    | head :: tail ->
Yea,ik I used this, because I could keep a track of easily.

2020-09-01 13:08 UTC, singhalshubh commented on benchmarks/graph500seq/kernel3.ml
> +  let size = n in
Done.

2020-09-01 15:49 UTC, kayceesrk commented
@singhalshubh how long does the kernel 2 and 3 run for the given inputs?

2020-09-01 16:34 UTC, singhalshubh commented
> @singhalshubh how long does the kernel 2 and 3 run for the given inputs?

If I take the scale as 2/3/4 it takes less than two  seconds to give the output! But as you increase the scale, the no of vertices being 2^scale increases drastically and so is the computation time. Also, the computation here I refer to is Kronecker one. Once kronecker is done, all kernels irrespective of input will take less than few seconds because of the probability kronecker was initialised with reducing the graph complexity drastically even though no of vertices are exponentially large!

2020-09-01 17:46 UTC, kayceesrk commented
Ok. Running for a few seconds is good for the sequential benchmark case since we have many benchmarks. When we have the parallel one, it would be useful to think about the options such that the baseline sequential case runs for ~100s, such that the parallel cases have enough work to parallelize. Also, it is important that the baseline sequential, and all the parallel runs (with different number of domains), run the algorithms on the same graph. Otherwise, it would be meaningless to compare the runtime numbers. Since we use a PRNG, if we use the same seed in the different runs, then the workload produced should be the same.

2020-09-01 17:48 UTC, singhalshubh commented
> Ok. Running for a few seconds is good for the sequential benchmark case since we have many benchmarks. When we have the parallel one, it would be useful to think about the options such that the baseline sequential case runs for ~100s, such that the parallel cases have enough work to parallelize. Also, it is important that the baseline sequential, and all the parallel runs (with different number of domains), run the algorithms on the same graph. Otherwise, it would be meaningless to compare the runtime numbers. Since we use a PRNG, if we use the same seed in the different runs, then the workload produced should be the same. 

Yes I absolutely agree! Thats why I am digging in more to find the parallel algorithms as a concept from the book!

2020-09-02 07:40 UTC, kayceesrk commented on run_config.json
> +        "macro_bench"
add `run_in_ci`

2020-09-02 07:40 UTC, kayceesrk commented on run_config.json
> +        "macro_bench"
add `run_in_ci`

2020-09-02 10:00 UTC, singhalshubh commented on benchmarks/graph500seq/kernel2.ml
> +(*For debugging*)
Do you mean the debugging code?

2020-09-02 10:03 UTC, kayceesrk approved these changes
Let's see if the CI passes with the new benchmarks.

2020-09-02 10:24 UTC, kayceesrk commented
This looks good to go. Merging it. Thanks @singhalshubh.

2020-09-02 10:24 UTC, merged