rename Json Files
ocaml-bench/sandmark pull request #315
Opened 2022-03-29 18:12 UTC by codeamic

Renamed  the following files
run_config.json -> sequential.json
multicore_parallel_run_config.json -> parallel_turing.json
multicore_parallel_navajo_run_config.json -> parallel_navajo.json
micro_multicore.json -> micro.json

2022-03-30 06:45 UTC, Sudha247 requested changes
Hi @codeamic! Thanks for the PR.

The renaming looks correct to me. But there are some more changes apart from the four file renames mentioned, could you look into why they show up please?

You will also need to propagate the renaming to other places it is used at. Let's take `run_config.json` for example; doing `git grep run_config.json` shows this:

```
Makefile:RUN_CONFIG_JSON ?= run_config.json
README.md:benchmarks as defined in the `run_config.json`
README.md:   `run_config.json`. This config file is used to generate dune files
README.md:   `run_config.json` and specified via the `RUN_BENCH_TARGET` variable
README.md:and the default value is `run_config.json`. This file lists the executable to
README.md:The `run_config.json` file may be filtered based on the tag. For example,
README.md:filters the `run_config.json` file to only contain the benchmarks tagged as
README.md:    `run_config.json` for sequential benchmarks and
README.md:    `multicore_parallel_run_config.json` for parallel benchmarks.
README.md: - **run_config.json** : Runs sequential benchmarks with stock OCaml variants in CI and sandmark-nightly on the IITM machine(turing)
README.md: - **multicore_parallel_run_config.json** : Runs parallel benchmarks with multicore OCaml in CI and sandmark-nightly on the IITM machine(turing)
README.md: - **multicore_parallel_navajo_run_config.json** : Runs parallel benchmarks with multicore OCaml in sandmark-nightly on Navajo (AMD EPYC 7551 32-Core Processor) machine
README.md:| RUN_CONFIG_JSON | Input file selection that contains the list of benchmarks | `run_config.json` | executing benchmark |
```
All these instances of `run_config.json` need to be renamed to `sequential.json`. Similarly for the other three files.

2022-03-30 12:01 UTC, codeamic commented
Hi Sudha, i just did the changes, thank you for the support,
some other files are showing i edited them which i didn't.

2022-03-30 12:08 UTC, codeamic reviewed
Hi Sudha, I just reviewed the files i made changes one, waiting for it to be merged

2022-03-31 04:49 UTC, Sudha247 reviewed
This is great, the spurious diff has disappeared now. Just some minor bits before we merge.

2022-03-31 04:49 UTC, Sudha247 commented on README.md
>  $ TAG='"macro_bench"' make run_config_filtered.json
```suggestion
$ TAG='"macro_bench"' make sequential_filtered.json
```
The filtered files should also be changed to their new names. Leave the `filtered` as such and edit the name. This needs to be updated in the `run_all*` scripts too.

2022-03-31 06:24 UTC, codeamic commented on README.md
>  $ TAG='"macro_bench"' make run_config_filtered.json
Hi Sudha, thank you for the support, i just did the new changes but couldn't find the run_config_filtered.json file itself.

2022-03-31 07:41 UTC, Sudha247 commented on README.md
>  $ TAG='"macro_bench"' make run_config_filtered.json
Nice work! You're right, `run_config_filtered.json` is created only after we run `TAG='"macro_bench"' make run_config_filtered.json`, so no need to modify that file.

Are you able to repeat this process for the other three files, like for example `run_all_parallel.sh` has `multicore_parallel_run_config_filtered.json`. `git grep` command should help here too. :)

2022-03-31 08:09 UTC, codeamic commented on README.md
>  $ TAG='"macro_bench"' make run_config_filtered.json
Yeah i did git grep run_config.json, you could see the changes in all the files. i made sure i changed that in all files. could you please check?

2022-03-31 17:20 UTC, Sudha247 commented on README.md
>  $ TAG='"macro_bench"' make run_config_filtered.json
Sorry if it was unclear; what I meant is the same process of replacing `*_filtered.json` with the new file name needs to be done for `multicore_parallel_run_config_filtered.json`, i.e it will be called `parallel_turing_filtered.json` and `multicore_parallel_navajo_run_config_filtered.json` will be `parallel_navajo_filtered.json`.

2022-03-31 17:52 UTC, codeamic commented on README.md
>  $ TAG='"macro_bench"' make run_config_filtered.json
Hi Sudha, no worries i just made the changes
could you please review?
Also, there is this file multicore_parallel_run_config_filtered_filtered_2domains, does it need renaming?

2022-04-01 14:50 UTC, codeamic commented on README.md
>  $ TAG='"macro_bench"' make run_config_filtered.json
Hi Sudha, thank you so much for your endless support, i just did the changes and modified the drone.yml file too. please review for merge or correction of errors, thank you.

2022-04-03 20:37 UTC, codeamic commented
Hello Sudha
Hope you had a good weekend, please i will be waiting for your reply on
what to do next
Regards.
Sango Pascal.

On Fri, 1 Apr 2022, 10:13 Sudha Parimala, ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In README.md
> <https://github.com/ocaml-bench/sandmark/pull/315#discussion_r840390961>:
>
> > @@ -177,13 +177,13 @@ current tags are:
>  The benchmarking machine `turing` is an Intel Xeon Gold 5120 CPU with 64GB of
>  RAM housed at IITM.
>
> -The `run_config.json` file may be filtered based on the tag. For example,
> +The `sequential.json` file may be filtered based on the tag. For example,
>
>  ```bash
>  $ TAG='"macro_bench"' make run_config_filtered.json
>
> Also, there is this file
> multicore_parallel_run_config_filtered_filtered_2domains, does it need
> renaming?
>
> Good point. Yes, we can call it
> parallel_turing_filtered_filtered_2domains.json. You can see how it's
> generated here:
> https://github.com/ocaml-bench/sandmark/blob/main/Makefile#L347-L348.
> This should make the CI happy I think. You might also want to edit the
> drone.yml file with the latest names.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ocaml-bench/sandmark/pull/315#discussion_r840390961>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AP663VIAJPYPC3I2VAA76ZTVC2435ANCNFSM5R7HVQZQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-04-04 05:11 UTC, Sudha247 reviewed
Some final bits in the CI before we can merge. The CI should ideally turn green after the changes.

2022-04-04 05:11 UTC, Sudha247 commented on .drone.yml
>    - TAG='"run_in_ci"' make multicore_parallel_run_config_filtered.json
```suggestion
  - TAG='"run_in_ci"' make parallel_turing_filtered.json
```

2022-04-04 05:11 UTC, Sudha247 commented on .drone.yml
>    - TAG='"macro_bench"' make multicore_parallel_run_config_filtered_filtered.json
```suggestion
  - TAG='"macro_bench"' make parallel_turing_filtered_filtered.json
```

2022-04-04 05:11 UTC, Sudha247 commented on .drone.yml
>    - TAG='"macro_bench"' make multicore_parallel_run_config_filtered_filtered.json
Same as above.

2022-04-04 05:11 UTC, Sudha247 commented on .drone.yml
>    - export OPAM_DISABLE_SANDBOXING=true
GitHub isn't allowing me to comment, but line 75 should be `TAG='"run_in_ci"' make sequential_filtered.json`

2022-04-04 06:29 UTC, codeamic commented on .drone.yml
>    - export OPAM_DISABLE_SANDBOXING=true
All good Sudha, i just did the requested changes.
Cheers.🙂

2022-04-04 06:48 UTC, codeamic commented
Hi Sudha, i commited the changes already .

2022-04-05 13:35 UTC, shakthimaan commented
> run_config.json -> sequential.json

If the filename is changed to `sequential.json`, the invocation should use `sequential_filtered.json`. For example:

```
$ make clean 
$ TAG='"run_in_ci"' make sequential_filtered.json 
$ USE_SYS_DUNE_HACK=1 RUN_CONFIG_JSON=sequential_filtered.json make ocaml-versions/5.0.0+trunk.bench
```

> multicore_parallel_run_config.json -> parallel_turing.json

Similarly,

```
$ make clean
$ TAG='"macro_bench"' make parallel_turing_filtered.json 
$ USE_SYS_DUNE_HACK=1 SANDMARK_CUSTOM_NAME=5.0.0 \
    RUN_BENCH_TARGET=run_orunchrt BUILD_BENCH_TARGET=multibench_parallel \
    RUN_CONFIG_JSON=parallel_turing_filtered.json \
    make ocaml-versions/5.0.0+trunk.bench
```

2022-04-05 15:11 UTC, codeamic commented
Hi @shakthimaan , please I don't  understand you. do you wand me to add the invocation in the README.md file?

2022-04-05 20:31 UTC, codeamic commented
Hi @shakthimaan , i did the changes already,  ould you please review

2022-04-06 16:40 UTC, shakthimaan commented
The parallel run is failing, and that needs to be fixed.

> + TAG='"run_in_ci"' make parallel_turing_filtered.json
> jq '{wrappers : .wrappers, benchmarks: [.benchmarks | .[] | select(.tags | index("run_in_ci") != null)]}' < parallel_turing.json > parallel_turing_filtered.json

The above is fine, and it produces a `parallel_turing_filtered.json` file.

> + TAG='"macro_bench"' make parallel_turing_filtered.json
> make: 'parallel_turing_filtered.json' is up to date.

This should be updated to:
```
TAG='"macro_bench"' make parallel_turing_filtered_filtered.json
```

2022-04-07 18:17 UTC, codeamic commented
Ok

2022-04-07 19:01 UTC, codeamic commented
Hi @shakthimaan, i made the changes, could you please check .

2022-04-08 03:12 UTC, shakthimaan commented
The change is required for `5.0.0+trunk+parallel`, and not for `5.0.0+stable+parallel`. Please see the build log at https://cloud.drone.io/ocaml-bench/sandmark/1154/4/2.

2022-04-08 16:17 UTC, codeamic commented
Ohh, sorry about that, i just maade the changes. But facing little problem to push

2022-04-08 17:10 UTC, shakthimaan commented
You need to revert the changes for `5.0.0+stable+parallel` as in the successful build at line #361:
https://cloud.drone.io/ocaml-bench/sandmark/1083/2/2

The `5.0.0.+trunk+parallel` entry still needs to be updated as mentioned in https://github.com/ocaml-bench/sandmark/pull/315#issuecomment-1090478279.

2022-04-08 21:30 UTC, codeamic commented
All done, could you please check if it is ok now?

2022-04-11 05:31 UTC, Sudha247 reviewed
The CI changes look fine, just a couple more updates should make it green.

2022-04-11 05:31 UTC, Sudha247 commented on .drone.yml
> +  - TAG='"macro_bench"' make parallel_turing_filtered.json
```suggestion
  - TAG='"macro_bench"' make parallel_turing_filtered_filtered.json
```

2022-04-11 05:31 UTC, Sudha247 commented on .drone.yml
> +  - TAG='"run_in_ci"' make parallel_turing_filtered_filtered.json
```suggestion
  - TAG='"run_in_ci"' make parallel_turing_filtered.json
```

2022-04-11 14:49 UTC, codeamic commented on .drone.yml
> +  - TAG='"run_in_ci"' make parallel_turing_filtered_filtered.json
Hi @Sudha247, glad you are back. i just made the changes  could you please check and let me know if everything is ok?

2022-04-11 16:35 UTC, shakthimaan commented on .drone.yml
> +  - TAG='"run_in_ci"' make parallel_turing_filtered_filtered.json
Kindly test the changes locally on your system before updating the PR. The steps can be run on an Ubuntu virtual machine or a Docker container.

2022-04-11 17:39 UTC, codeamic commented
ok

2022-04-12 06:08 UTC, Sudha247 approved these changes
LGTM! Are you able to rebase your branch to latest main, so we can merge it please? Please also note that there could be conflicts with #316 depending on which on is merged first.

2022-04-12 06:39 UTC, Sudha247 commented
The GitHub interface tells me these files have merge-conflicts:

```
multicore_parallel_navajo_run_config.json
multicore_parallel_run_config.json
run_config.json
```

`git pull <upstream> main` should fetch the latest changes from the `main` branch to your branch, after which the merge conflicts will be highlighted. There have been more entries added to the above mentioned files in #322, and the renamed files now need to include those too.

2022-04-12 16:26 UTC, Sudha247 commented
The merge conflicts are still present unfortunately. Can you try to do `git fetch --all` before pulling it.

```
git remote add upstream https://github.com/ocaml-bench/sandmark.git
git fetch --all
git pull upstream main
```

This should fetch the latest `main` branch to your local branch.

2022-04-13 10:14 UTC, codeamic commented
Hi Sudha, thank you for the help. I think it is all good for merging now.

2022-06-21 16:27 UTC, shakthimaan commented
Sandmark has been updated to build for 5.1.0+trunk. @ElectreAAS Please review the conflicting files and update the same for the CI.

2022-06-27 09:57 UTC, ElectreAAS commented
> Sandmark has been updated to build for 5.1.0+trunk. @ElectreAAS Please review the conflicting files and update the same for the CI.
The only conflict is the `.drone.yml` file which was removed from main in #354.

2026-03-24 05:28 UTC, tmcgilchrist commented
I'm triaging open PRs on this repository. At the current time we can't take this contribution, it is unclear if it still applies 4 years later.

2026-03-24 05:28 UTC, closed without merging